[llm]
model_name = "hf.co/msu-rcc-lair/RuadaptQwen2.5-32B-instruct-GGUF"

[paths]
unzip_dir = "temp_unzipped"
prompts = "app/llm_prompts/prompts.json"
errors_list = "app/llm_prompts/errors_list.json"
rules = "app/llm_prompts/rules.json"
logs = "logs/app.log"
project_root = "temp_unzipped"  # Оставляем пустым, так как путь будет динамическим

[logging]
level = "INFO"
file = "logs/app.log"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
max_bytes = 10485760  # 10 MB
backup_count = 5

[pdf]
wkhtmltopdf_path = "/usr/local/bin/wkhtmltopdf"  # TODO: Замените на ваш путь к wkhtmltopdf

